name: Package Classic

on:
  push:
    branches:
      - classic
    tags:
      - '**-classic*'
    paths-ignore:
      - '.github/**'



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Package Classic Era
      uses: BigWigsMods/packager@master
      with:
        args: -g classic
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
